export const PERMISSIONS = {
  MANAGE_USERS: 'manage_users',
  VIEW_ALL_DEALS: 'view_all_deals',
  MANAGE_DEALS: 'manage_deals',
  MANAGE_LEADS: 'manage_leads',
  CLOSE_DEALS: 'close_deals',
  ARCHIVE_DEALS: 'archive_deals',
  STOCK_CONFIRM: 'stock_confirm',
  FINANCE_APPROVE: 'finance_approve',
  ADMIN_APPROVE: 'admin_approve',
  CONFIRM_SHIPMENT: 'confirm_shipment',
  MANAGE_INVENTORY: 'manage_inventory',
  MANAGE_PRODUCTS: 'manage_products',
  VIEW_ALL_CLIENTS: 'view_all_clients',
  CREATE_INVENTORY_IN: 'create_inventory_in',
  EDIT_CLIENT: 'edit_client',
  EDIT_CLOSED_DEAL: 'edit_closed_deal',
  MANAGE_CONTRACT: 'manage_contract',
  APPROVE_DEAL: 'approve_deal',
  SHIPMENT_EXECUTE: 'shipment_execute',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS: Permission[] = Object.values(PERMISSIONS);

export const DEFAULT_PERMISSIONS: Record<string, Permission[]> = {
  SUPER_ADMIN: [...ALL_PERMISSIONS],
  ADMIN: [...ALL_PERMISSIONS],
  OPERATOR: [
    PERMISSIONS.MANAGE_LEADS,
    PERMISSIONS.VIEW_ALL_CLIENTS,
  ],
  MANAGER: [
    PERMISSIONS.MANAGE_DEALS,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.VIEW_ALL_CLIENTS,
    PERMISSIONS.EDIT_CLIENT,
  ],
  ACCOUNTANT: [
    PERMISSIONS.FINANCE_APPROVE,
    PERMISSIONS.VIEW_ALL_DEALS,
    PERMISSIONS.MANAGE_CONTRACT,
  ],
  WAREHOUSE: [
    PERMISSIONS.STOCK_CONFIRM,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.VIEW_ALL_DEALS,
    PERMISSIONS.CREATE_INVENTORY_IN,
  ],
  WAREHOUSE_MANAGER: [
    PERMISSIONS.STOCK_CONFIRM,
    PERMISSIONS.CONFIRM_SHIPMENT,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.VIEW_ALL_DEALS,
    PERMISSIONS.CREATE_INVENTORY_IN,
    PERMISSIONS.SHIPMENT_EXECUTE,
  ],
};
