"""Generate frontend/src/pages/priceComparisonData.ts from repo-root price_comparison_polygraph.html."""
from __future__ import annotations

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
HTML = ROOT / "price_comparison_polygraph.html"
OUT = ROOT / "frontend" / "src" / "pages" / "priceComparisonData.ts"

LINE_RE = re.compile(
    r'^\s*\{cat:"((?:\\.|[^"\\])*)",'
    r' us:"((?:\\.|[^"\\])*)",'
    r' them:"((?:\\.|[^"\\])*)",'
    r' comp:"((?:\\.|[^"\\])*)",'
    r' usp:(\d+|null),'
    r' theirp:(\d+|null),'
    r' type:"((?:\\.|[^"\\])*)"\}\s*,?\s*$',
)


def js_string_unescape(s: str) -> str:
    """Undo JS-style escapes inside double-quoted segments (e.g. \\\" -> \")."""
    out: list[str] = []
    i = 0
    while i < len(s):
        if s[i] == "\\" and i + 1 < len(s):
            nxt = s[i + 1]
            if nxt == '"':
                out.append('"')
                i += 2
                continue
            if nxt == "\\":
                out.append("\\")
                i += 2
                continue
        out.append(s[i])
        i += 1
    return "".join(out)


def main() -> int:
    if not HTML.is_file():
        print(f"Missing {HTML}", file=sys.stderr)
        return 1

    text = HTML.read_text(encoding="utf-8")
    rows: list[tuple[str, str, str, str, int | None, int | None, str]] = []
    for line in text.splitlines():
        m = LINE_RE.match(line)
        if not m:
            continue
        cat, us, them, comp, usp_s, theirp_s, typ = m.groups()
        cat = js_string_unescape(cat)
        us = js_string_unescape(us)
        them = js_string_unescape(them)
        comp = js_string_unescape(comp)
        typ = js_string_unescape(typ)
        usp = None if usp_s == "null" else int(usp_s)
        theirp = None if theirp_s == "null" else int(theirp_s)
        rows.append((cat, us, them, comp, usp, theirp, typ))

    if not rows:
        print("No rows parsed from HTML", file=sys.stderr)
        return 1

    header = """// AUTO-GENERATED by frontend/scripts/extract_price_comparison_data.py from price_comparison_polygraph.html
// Regenerate after editing the HTML source list.

export type MatchType = 'Точное' | 'Потенциальное';

export type Competitor = 'Yann' | 'Bit Trade' | 'Avanta Trade' | 'Foil Trading';

export type PriceRow = {
  key: string;
  category: string;
  ourProduct: string;
  competitorProduct: string;
  competitor: Competitor;
  ourPrice: number;
  competitorPrice: number | null;
  matchType: MatchType;
};

export const PRICE_ROWS: PriceRow[] = [
"""

    body_lines: list[str] = []
    for i, (cat, us, them, comp, usp, theirp, typ) in enumerate(rows, start=1):
        if usp is None:
            raise ValueError(f"Row {i}: usp is null (unexpected)")
        cp_json = "null" if theirp is None else str(theirp)
        body_lines.append(
            "  {"
            f' key: "{i}", '
            f"category: {json.dumps(cat, ensure_ascii=False)}, "
            f"ourProduct: {json.dumps(us, ensure_ascii=False)}, "
            f"competitorProduct: {json.dumps(them, ensure_ascii=False)}, "
            f"competitor: {json.dumps(comp, ensure_ascii=False)} as Competitor, "
            f"ourPrice: {usp}, "
            f"competitorPrice: {cp_json}, "
            f"matchType: {json.dumps(typ, ensure_ascii=False)} as MatchType "
            "},",
        )

    footer = "];\n"
    OUT.write_text(header + "\n".join(body_lines) + "\n" + footer, encoding="utf-8")
    print(f"Wrote {len(rows)} rows -> {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
