import type { ReactNode } from 'react';
import type { MenuProps } from 'antd';
import type { Icon } from '@phosphor-icons/react';
import {
  Archive,
  ArrowsLeftRight,
  Bank,
  BellSimple,
  Boat,
  BookOpen,
  CalendarDots,
  Car,
  CashRegister,
  ChartBar,
  ChartLineUp,
  ChatCircle,
  CheckCircle,
  CheckSquare,
  ClipboardText,
  Clock,
  ClockCounterClockwise,
  ClockCountdown,
  Copy,
  CurrencyCircleDollar,
  Eye,
  Factory,
  FileText,
  Flask,
  FlowArrow,
  Gauge,
  GearSix,
  GlobeHemisphereEast,
  Graph,
  Handshake,
  IdentificationCard,
  Kanban,
  ListChecks,
  ListMagnifyingGlass,
  Megaphone,
  Newspaper,
  Notepad,
  Package,
  PaperPlaneTilt,
  Phone,
  PhoneCall,
  Presentation,
  Prohibit,
  Receipt,
  Robot,
  Scales,
  SealCheck,
  Signature,
  Sparkle,
  Star,
  Storefront,
  Tray,
  TreeStructure,
  Truck,
  User,
  UserFocus,
  UsersFour,
  UsersThree,
  Wallet,
  Warehouse,
  Waveform,
} from '@phosphor-icons/react';

/**
 * Иконки бокового меню в новом дизайне — Phosphor вместо Ant Design.
 * Ключ — `key` пункта меню в Layout.tsx. Пункт, которого здесь нет, остаётся со
 * своей старой иконкой, поэтому новый пункт меню ничего не сломает.
 */
const ICON_BY_KEY: Record<string, Icon> = {
  '/dashboard': Gauge,
  '/clients': UsersThree,
  '/clients/duplicates': Copy,
  '/reviews': Star,
  '/contracts': FileText,
  '/power-of-attorney': Signature,
  '/deals': Handshake,
  '/inventory/products': Package,
  '/inventory/groups': TreeStructure,
  '/inventory/warehouse': Warehouse,
  '/inventory/audit-check': ClipboardText,
  '/shipment': Truck,
  '/stock-confirmation': CheckSquare,
  '/deals/approval': SealCheck,
  '/warehouse-manager': Storefront,
  '/warehouse-manager-incoming': Tray,
  '/my-loading-tasks': ListChecks,
  '/my-vehicle': Car,
  'almanac-group': BookOpen,
  '/tasks': Kanban,
  '/notes-board': Notepad,
  '/finance/cashbox?tab=debtors': Receipt,
  '/finance/review': Scales,
  '/finance/expenses': Wallet,
  '/finance/cashbox': CashRegister,
  '/finance/balance': Bank,
  '/foreign-trade/suppliers': Factory,
  '/foreign-trade/map': GlobeHemisphereEast,
  '/foreign-trade/import-orders': Boat,
  '/foreign-trade/process-board': FlowArrow,
  '/foreign-trade/exchange-rates': CurrencyCircleDollar,
  '/deals/closed': CheckCircle,
  '/deals/audit-check': ListMagnifyingGlass,
  '/deals/archived': Archive,
  '/inventory/movements': ArrowsLeftRight,
  '/manager/client-activity': CalendarDots,
  '/manager/reanimation': Megaphone,
  '/manager/dead-products': Prohibit,
  '/manager/payment-overdue': ClockCountdown,
  '/analytics/calls': Phone,
  '/analytics/contact-matrix': Graph,
  '/analytics/note-audit': Robot,
  '/analytics/lamination-kg-usage': Flask,
  '/analytics': ChartBar,
  '/history-analytics': ClockCounterClockwise,
  '/analytics/market': ChartLineUp,
  '/analytics/department-report': Presentation,
  '/profile': IdentificationCard,
  '/changelog': Newspaper,
  '/team': UsersFour,
  '/users': User,
  '/worker-audit': UserFocus,
  '/attendance': Clock,
  '/admin/activity-log': Eye,
  '/settings/company': GearSix,
  '/ai-assistant': Sparkle,
  '/ai-assistant/transcribe': Waveform,
  '/ai-assistant/call-audits': PhoneCall,
  '/rop-agent': Robot,
  '/messages': ChatCircle,
  'notifications-group': BellSimple,
  '/notifications': BellSimple,
  '/notifications/broadcast': PaperPlaneTilt,
};

type MenuItem = NonNullable<MenuProps['items']>[number];

/** Заменяет иконки пунктов меню (и вложенных) на Phosphor. */
export function withModernMenuIcons(items: MenuProps['items']): MenuProps['items'] {
  return items?.map((item): MenuItem => {
    if (!item || !('key' in item)) return item;
    const PhIcon = typeof item.key === 'string' ? ICON_BY_KEY[item.key] : undefined;
    const next = { ...item } as MenuItem & { icon?: ReactNode; children?: MenuProps['items'] };
    if (PhIcon && 'icon' in next && next.icon) next.icon = <PhIcon size={18} />;
    if ('children' in next && next.children) next.children = withModernMenuIcons(next.children);
    return next;
  });
}
