export {
  SQL_ANALYTICS_TZ,
  SQL_LINE_REVENUE_DI,
  SQL_EFFECTIVE_ITEM_TS,
  SQL_EFFECTIVE_ITEM_DATE_TASHKENT,
  SQL_DEALS_ACTIVE_FILTER,
  SQL_DEALS_SHIPPED_CLOSED_FILTER,
} from './sqlFragments';
